{{- range $azs := .Values.azs }}
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: {{ $azs.name }}
spec:
  securityGroups: {{ $azs.sgs }}
  subnet: {{ $azs.subnet }}
{{- end }}